# Configurations
title:            Hyolll's Blog
author:           Hyolll
email:            leehyo96@naver.com
description: >
  My GitHub Pages powered by Jekyll GitBook theme.

version:          1.0
gitbook_version:  3.2.3

url:              "https://hyolll.github.io"
baseurl:          "" # 반드시 비워둡니다.

remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

permalink: /:categories/:title/
